version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: job_portal_db
    environment:
      MYSQL_DATABASE: job_portal
      MYSQL_ROOT_PASSWORD: 8008
    ports:
      - "3037:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    container_name: job_portal_redis
    ports:
      - "6379:6379"

  app:
    build: ./python_db
    container_name: job_portal_app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=8008
      - MYSQL_SERVER=db
      - MYSQL_PORT=3306
      - MYSQL_DB=job_portal
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

volumes:
  db_data:

services:
 frontend:
  build: ./frontend
  container_name: react_app
  ports:
   - "8050:8080"
