version: '3.8'

services:
  test_db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test_job_portal
      MYSQL_ROOT_PASSWORD: 8008
    ports:
      - "3307:3306"

  test_redis:
    image: redis:6.2-alpine
    ports:
      - "6380:6379"
